# Generated by Django 5.0.1 on 2024-01-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
