# Generated by Django 5.0.1 on 2024-01-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_userdata_email_confirmation_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email_confirmation_token',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='email_confirmed',
        ),
    ]
