# Generated by Django 5.0.1 on 2024-01-27 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_usr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usr',
            new_name='user',
        ),
    ]
